mmotm 2021-01-12-01-57 uploaded (NR_SWAPCACHE in mm/)
On Tue, 12 Jan 2021 12:38:18 -0800 Randy Dunlap <rdunlap@infradead.org> wrote:

> On 1/12/21 1:58 AM, akpm@linux-foundation.org wrote:
> > The mm-of-the-moment snapshot 2021-01-12-01-57 has been uploaded to
> >
> >    https://www.ozlabs.org/~akpm/mmotm/
> >
> > mmotm-readme.txt says
> >
> > README for mm-of-the-moment:
> >
> > https://www.ozlabs.org/~akpm/mmotm/
> >
> > This is a snapshot of my -mm patch queue.  Uploaded at random hopefully
> > more than once a week.
> >
>
> on i386 and x86_64:
>
> when CONFIG_SWAP is not set/enabled:
>
> ../mm/migrate.c: In function ‘migrate_page_move_mapping’:
> ../mm/migrate.c:504:35: error: ‘NR_SWAPCACHE’ undeclared (first use in this function); did you mean ‘QC_SPACE’?
>     __mod_lruvec_state(old_lruvec, NR_SWAPCACHE, -nr);
>                                    ^~~~~~~~~~~~
>
> ../mm/memcontrol.c:1529:20: error: ‘NR_SWAPCACHE’ undeclared here (not in a function); did you mean ‘SGP_CACHE’?
>   { "swapcached",   NR_SWAPCACHE   },
>                     ^~~~~~~~~~~~

Thanks.  I did the below.

But we're still emitting "Node %d SwapCached: 0 kB" in sysfs when
CONFIG_SWAP=n, which is probably wrong.  Shakeel, can you please have a
think?

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>